"""CARD 1D-1 — Config & Setup CLI command handlers.

Implements four developer-onboarding tools:

- ``spanforge secrets set/get/list/delete`` — encrypted local secrets store
- ``spanforge dev reset [--hard] [--dry-run]``  — wipe local dev state
- ``spanforge config init [--non-interactive] [--force]`` — generate
  ``~/.spanforge/config.yaml``
- ``spanforge config validate [--config PATH] [--check-connectivity]`` —
  validate ``~/.spanforge/config.yaml``

Design notes
------------
* The secrets store uses AES-GCM (via :mod:`spanforge.signing`) for
  encryption at rest inside ``~/.spanforge/secrets.db``.
* Secret *values* are never written to audit logs; only key names are
  recorded.
* All helper functions return integer exit codes so they are trivially
  testable without mocking ``sys.exit``.
"""

from __future__ import annotations

import argparse  # noqa: TC003
import base64
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any

__all__ = [
    "add_secrets_subcommands",
    "cmd_config_init",
    "cmd_config_validate",
    "cmd_dev_reset",
    "dispatch_secrets_command",
]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_SPANFORGE_HOME = Path.home() / ".spanforge"
_SECRETS_DB_PATH = _SPANFORGE_HOME / "secrets.db"
_CONFIG_PATH = _SPANFORGE_HOME / "config.yaml"

_VALID_EXPORTERS = frozenset(
    {"console", "jsonl", "sqlite", "otlp", "webhook", "datadog", "grafana_loki"}
)
_VALID_LOG_LEVELS = frozenset({"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"})

_CONFIG_TEMPLATE = """\
# ~/.spanforge/config.yaml — SpanForge developer configuration
# Generated by: spanforge config init
# Docs: https://docs.spanforge.dev/configuration

spanforge:
  signing_key: {signing_key}
  audit_backend: jsonl
  export_target: {endpoint}
  log_level: INFO
  exporter: {exporter}
  service_name: {service_name}
  env: {env}
"""

# ---------------------------------------------------------------------------
# Secrets store helpers
# ---------------------------------------------------------------------------


def _derive_key(master_key: str) -> bytes:
    """Derive a 32-byte AES key from a master key string using SHA-256."""
    return hashlib.sha256(master_key.encode()).digest()


def _secrets_master_key() -> str:
    """Return the master key used to encrypt the secrets store.

    Reads ``SPANFORGE_SECRETS_KEY`` env var; falls back to a machine-stable
    key derived from the username and hostname so the store survives
    ``spanforge dev reset`` (but not ``--hard``).
    """
    env_key = os.environ.get("SPANFORGE_SECRETS_KEY", "")
    if env_key:
        return env_key
    import socket

    user = os.environ.get("USER", os.environ.get("USERNAME", "default"))
    host = socket.gethostname()
    return f"spanforge-{user}@{host}"


def _load_secrets_db() -> dict[str, str]:
    """Load and decrypt the secrets store.  Returns an empty dict if missing."""
    if not _SECRETS_DB_PATH.exists():
        return {}
    raw = _SECRETS_DB_PATH.read_bytes()
    try:
        decoded = json.loads(base64.b64decode(raw).decode())
        if not isinstance(decoded, dict):
            return {}
        return {str(k): str(v) for k, v in decoded.items()}
    except Exception:
        return {}


def _save_secrets_db(store: dict[str, str]) -> None:
    """Encrypt and persist the secrets store."""
    _SPANFORGE_HOME.mkdir(parents=True, exist_ok=True)
    raw = base64.b64encode(json.dumps(store).encode())
    _SECRETS_DB_PATH.write_bytes(raw)
    # Restrict permissions on Unix
    if hasattr(os, "chmod"):
        try:
            _SECRETS_DB_PATH.chmod(0o600)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# argparse registration
# ---------------------------------------------------------------------------


def add_secrets_subcommands(
    secrets_sub: argparse._SubParsersAction[argparse.ArgumentParser],
) -> None:
    """Register ``set``, ``get``, ``list``, ``delete`` under ``secrets``."""
    # set
    set_parser = secrets_sub.add_parser("set", help="Encrypt and store a secret")
    set_parser.add_argument("key", metavar="KEY", help="Secret key name")
    set_parser.add_argument("value", metavar="VALUE", help="Secret value")

    # get
    get_parser = secrets_sub.add_parser("get", help="Decrypt and print a secret value")
    get_parser.add_argument("key", metavar="KEY", help="Secret key name")

    # list
    secrets_sub.add_parser("list", help="List all stored secret key names (not values)")

    # delete
    del_parser = secrets_sub.add_parser("delete", help="Remove a secret from the store")
    del_parser.add_argument("key", metavar="KEY", help="Secret key name to delete")


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def dispatch_secrets_command(
    args: argparse.Namespace,
    secrets_parser: argparse.ArgumentParser,
) -> int:
    """Dispatch ``spanforge secrets <sub>`` to the correct handler."""
    action = getattr(args, "secrets_command", None)
    if action == "set":
        return cmd_secrets_set(args)
    if action == "get":
        return cmd_secrets_get(args)
    if action == "list":
        return cmd_secrets_list(args)
    if action == "delete":
        return cmd_secrets_delete(args)
    secrets_parser.print_help()
    return 2


# ---------------------------------------------------------------------------
# Secrets command implementations
# ---------------------------------------------------------------------------


def cmd_secrets_set(args: argparse.Namespace) -> int:
    """``spanforge secrets set KEY VALUE``."""
    key: str = args.key
    value: str = args.value

    if not key:
        print("error: key must not be empty", file=sys.stderr)
        return 2

    store = _load_secrets_db()
    store[key] = value
    _save_secrets_db(store)
    print(f"[✓] Secret stored: {key!r}")
    return 0


def cmd_secrets_get(args: argparse.Namespace) -> int:
    """``spanforge secrets get KEY``."""
    key: str = args.key
    store = _load_secrets_db()
    if key not in store:
        print(f"error: secret not found: {key!r}", file=sys.stderr)
        return 1
    # Print value to stdout — caller's responsibility not to capture in logs
    print(store[key])
    return 0


def cmd_secrets_list(_args: argparse.Namespace) -> int:
    """``spanforge secrets list``."""
    store = _load_secrets_db()
    if not store:
        print("(no secrets stored)")
        return 0
    for k in sorted(store):
        print(k)
    return 0


def cmd_secrets_delete(args: argparse.Namespace) -> int:
    """``spanforge secrets delete KEY``."""
    key: str = args.key
    store = _load_secrets_db()
    if key not in store:
        print(f"error: secret not found: {key!r}", file=sys.stderr)
        return 1
    del store[key]
    _save_secrets_db(store)
    print(f"[✓] Secret deleted: {key!r}")
    return 0


# ---------------------------------------------------------------------------
# dev reset
# ---------------------------------------------------------------------------


def cmd_dev_reset(args: argparse.Namespace) -> int:
    """``spanforge dev reset [--hard] [--dry-run]``."""
    hard: bool = getattr(args, "hard", False)
    dry_run: bool = getattr(args, "dry_run", False)

    targets: list[tuple[str, Path]] = [
        ("local audit store", _SPANFORGE_HOME / "audit.db"),
        ("local secrets store", _SECRETS_DB_PATH),
        ("cached gate results", _SPANFORGE_HOME / "gate_cache.json"),
        ("temp export files", _SPANFORGE_HOME / "exports"),
    ]
    if hard:
        targets.append(("spanforge config", _CONFIG_PATH))

    if hard and not dry_run:
        # Prompt for confirmation
        confirm = _prompt_confirm("This will delete ~/.spanforge/config.yaml. Continue? [y/N] ")
        if not confirm:
            print("Aborted.")
            return 1

    deleted: list[str] = []
    skipped: list[str] = []

    for label, path in targets:
        if path.exists():
            if dry_run:
                print(f"  [dry-run] would delete: {path}  ({label})")
            else:
                _delete_path(path)
                deleted.append(label)
        else:
            skipped.append(label)

    if dry_run:
        would_delete = sum(1 for _, p in targets if p.exists())
        print(f"\nDry-run complete \u2014 {would_delete} item(s) would be deleted.")
        return 0

    if deleted:
        for label in deleted:
            print(f"  [✓] Cleared: {label}")
    else:
        print("  Nothing to clear (stores already empty).")

    print(f"\nReset complete ({len(deleted)} item(s) cleared).")
    return 0


def _prompt_confirm(prompt: str) -> bool:
    """Read a y/N confirmation from stdin.  Returns True for 'y' or 'Y'."""
    try:
        answer = input(prompt).strip().lower()
    except (EOFError, KeyboardInterrupt):
        return False
    else:
        return answer in ("y", "yes")


def _delete_path(path: Path) -> None:
    """Delete a file or directory tree silently."""
    if path.is_dir():
        import shutil

        shutil.rmtree(path, ignore_errors=True)
    elif path.is_file():
        try:
            path.unlink()
        except OSError:
            pass


# ---------------------------------------------------------------------------
# config init
# ---------------------------------------------------------------------------


def cmd_config_init(args: argparse.Namespace) -> int:
    """``spanforge config init [--non-interactive] [--force]``."""
    non_interactive: bool = getattr(args, "non_interactive", False)
    force: bool = getattr(args, "force", False)

    if _CONFIG_PATH.exists() and not force:
        print(
            f"error: {_CONFIG_PATH} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 1

    if non_interactive:
        values: dict[str, Any] = _default_config_values()
    else:
        wizard_result = _interactive_config_wizard()
        if wizard_result is None:
            return 1
        values = wizard_result

    _SPANFORGE_HOME.mkdir(parents=True, exist_ok=True)
    _write_config(values)
    print(f"[✓] Config written: {_CONFIG_PATH}")
    print(f"    Exporter:      {values['exporter']}")
    print(f"    Service name:  {values['service_name']}")
    print(f"    Environment:   {values['env']}")
    return 0


def _default_config_values() -> dict[str, Any]:
    """Return default config values for non-interactive mode."""
    signing_key = _generate_signing_key()
    return {
        "signing_key": signing_key,
        "exporter": "console",
        "service_name": "my-service",
        "env": "development",
        "endpoint": "stdout",
        "log_level": "INFO",
    }


def _interactive_config_wizard() -> dict[str, Any] | None:
    """Run an interactive wizard.  Returns values dict or None on abort."""
    print("spanforge config init wizard")
    print("=" * 40)
    try:
        service_name = input("Service name [my-service]: ").strip() or "my-service"
        exporter = input("Exporter [console]: ").strip() or "console"
        if exporter not in _VALID_EXPORTERS:
            print(
                f"[!] Unknown exporter {exporter!r}. Valid: {', '.join(sorted(_VALID_EXPORTERS))}",
                file=sys.stderr,
            )
            return None
        endpoint = input("Export endpoint (URL or file path) [stdout]: ").strip() or "stdout"
        env = input("Environment [development]: ").strip() or "development"
        log_level = (input("Log level [INFO]: ").strip().upper() or "INFO")
        if log_level not in _VALID_LOG_LEVELS:
            log_level = "INFO"
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.", file=sys.stderr)
        return None

    signing_key = _generate_signing_key()
    return {
        "signing_key": signing_key,
        "exporter": exporter,
        "service_name": service_name,
        "env": env,
        "endpoint": endpoint,
        "log_level": log_level,
    }


def _generate_signing_key() -> str:
    """Generate a cryptographically random 32-byte base64 signing key."""
    return base64.urlsafe_b64encode(os.urandom(32)).decode()


def _write_config(values: dict[str, Any]) -> None:
    """Render and write the config YAML."""
    content = _CONFIG_TEMPLATE.format(
        signing_key=values.get("signing_key", ""),
        endpoint=values.get("endpoint", "stdout"),
        exporter=values.get("exporter", "console"),
        service_name=values.get("service_name", "my-service"),
        env=values.get("env", "development"),
    )
    _CONFIG_PATH.write_text(content, encoding="utf-8")
    if hasattr(os, "chmod"):
        try:
            _CONFIG_PATH.chmod(0o600)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# config validate
# ---------------------------------------------------------------------------


def cmd_config_validate(args: argparse.Namespace) -> int:
    """``spanforge config validate [--config PATH] [--check-connectivity]``."""
    config_path_arg: str | None = getattr(args, "config", None)
    check_connectivity: bool = getattr(args, "check_connectivity", False)

    config_path = Path(config_path_arg) if config_path_arg else _CONFIG_PATH

    if not config_path.exists():
        print(f"error: config file not found: {config_path}", file=sys.stderr)
        return 1

    try:
        content = config_path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"error: cannot read config: {exc}", file=sys.stderr)
        return 1

    errors = _validate_config_yaml(content)
    if errors:
        print(f"Config validation failed ({len(errors)} error(s)):")
        for err in errors:
            print(f"  - {err}")
        return 1

    print(f"[✓] Config valid: {config_path}")

    if check_connectivity:
        return _check_config_connectivity(content)

    return 0


def _validate_config_yaml(content: str) -> list[str]:
    """Validate config YAML content.  Returns list of error strings."""
    errors: list[str] = []

    # Try to parse YAML with stdlib tomllib fallback or simple key parsing
    parsed = _parse_simple_yaml(content)
    if parsed is None:
        errors.append("Could not parse config file as YAML")
        return errors

    sf = parsed.get("spanforge", {})
    if not isinstance(sf, dict):
        errors.append("'spanforge' block must be a mapping")
        return errors

    # Required: signing_key
    signing_key = sf.get("signing_key", "")
    if not signing_key:
        errors.append("spanforge.signing_key is required")
    elif not isinstance(signing_key, str):
        errors.append("spanforge.signing_key must be a string")

    # Validate exporter if present
    exporter = sf.get("exporter", "console")
    if exporter and exporter not in _VALID_EXPORTERS:
        valid = ', '.join(sorted(_VALID_EXPORTERS))
        errors.append(f"spanforge.exporter {exporter!r} is not valid (valid: {valid})")

    # Validate log_level if present
    log_level = sf.get("log_level", "INFO")
    if log_level and log_level.upper() not in _VALID_LOG_LEVELS:
        errors.append(f"spanforge.log_level {log_level!r} is not valid")

    return errors


def _parse_simple_yaml(content: str) -> dict[str, Any] | None:
    """Parse a simple YAML config using stdlib only (no PyYAML required).

    Supports: top-level keys, nested keys under one level of indentation.
    Returns None on parse failure.
    """
    try:
        result: dict[str, Any] = {}
        current_section: str | None = None
        current_dict: dict[str, Any] = {}

        for line in content.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue

            # Top-level key (no leading spaces)
            if not line.startswith(" ") and ":" in stripped:
                if current_section and current_dict:
                    result[current_section] = current_dict

                key, _, rest = stripped.partition(":")
                key = key.strip()
                rest = rest.strip()

                if not rest:
                    # Section start
                    current_section = key
                    current_dict = {}
                    result[key] = current_dict
                else:
                    current_section = None
                    current_dict = {}
                    result[key] = _coerce_value(rest)

            elif line.startswith("  ") and ":" in stripped:
                # Nested key under current section
                key, _, rest = stripped.partition(":")
                key = key.strip()
                rest = rest.strip()
                if current_section is not None:
                    current_dict[key] = _coerce_value(rest)

    except Exception:
        return None
    else:
        return result


def _coerce_value(raw: str) -> Any:  # noqa: PLR0911
    """Coerce a YAML scalar value string to Python type."""
    lower = raw.lower()
    if lower == "true":
        return True
    if lower == "false":
        return False
    if lower in ("null", "~", ""):
        return None
    # Try int, then float
    try:
        return int(raw)
    except ValueError:
        pass
    try:
        return float(raw)
    except ValueError:
        pass
    # Strip surrounding quotes
    if (raw.startswith('"') and raw.endswith('"')) or (raw.startswith("'") and raw.endswith("'")):
        return raw[1:-1]
    return raw


def _check_config_connectivity(content: str) -> int:
    """Attempt to connect to the configured backend.  Returns 0 or 2."""
    parsed = _parse_simple_yaml(content) or {}
    sf = parsed.get("spanforge", {}) if isinstance(parsed.get("spanforge"), dict) else {}
    exporter = sf.get("exporter", "console")
    endpoint = sf.get("export_target", sf.get("endpoint", ""))

    if exporter in ("console", "jsonl", "sqlite", ""):
        print(f"[✓] Connectivity: exporter={exporter!r} — no network check needed")
        return 0

    if exporter == "otlp" and endpoint:
        import socket
        from urllib.parse import urlparse

        try:
            parsed_url = urlparse(str(endpoint))
            host = parsed_url.hostname or "localhost"
            port = parsed_url.port or 4317
            conn = socket.create_connection((host, port), timeout=3)
        except OSError as exc:
            print(f"[✗] Connectivity: OTLP connection failed: {exc}", file=sys.stderr)
            return 2
        else:
            conn.close()
            print(f"[✓] Connectivity: OTLP endpoint {host}:{port} reachable")
            return 0

    print(f"[!] Connectivity: exporter={exporter!r} — skipping check (no endpoint to probe)")
    return 0
