apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spanforge.fullname" . }}
  labels:
    {{- include "spanforge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spanforge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spanforge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ .name | default (include "spanforge.fullname" $) }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
