"""Type stubs for spanforge.sdk.identity (DX-001)."""

from __future__ import annotations

from typing import Any

from spanforge.sdk._base import SFClientConfig, SFServiceClient
from spanforge.sdk._types import (
    APIKeyBundle,
    JWTClaims,
    MagicLinkResult,
    RateLimitInfo,
    TokenIntrospectionResult,
    TOTPEnrollResult,
)

class SFIdentityClient(SFServiceClient):
    def __init__(self, config: SFClientConfig | None = None) -> None: ...
    def refresh_token(self) -> str: ...
    def issue_api_key(
        self,
        *,
        scopes: list[str] | None = None,
        project_id: str = "",
        expires_in_days: int = 365,
        ip_allowlist: list[str] | None = None,
        test_mode: bool = False,
    ) -> APIKeyBundle: ...
    def issue_magic_link(self, email: str) -> MagicLinkResult: ...
    def rotate_key(self, key_id: str) -> APIKeyBundle: ...
    def revoke_key(self, key_id: str) -> None: ...
    def create_session(self, api_key: str) -> str: ...
    def verify_token(self, jwt: str) -> JWTClaims: ...
    def introspect(self, token: str) -> TokenIntrospectionResult: ...
    def enroll_totp(self, key_id: str) -> TOTPEnrollResult: ...
    def verify_backup_code(self, key_id: str, code: str) -> bool: ...
    def saml_metadata(self) -> str: ...
    def check_rate_limit(self, key_id: str) -> RateLimitInfo: ...
    def record_request(self, key_id: str) -> bool: ...
    def check_ip_allowlist(self, key_id: str, ip: str) -> None: ...
    def get_jwks(self) -> dict[str, Any]: ...
    def require_scope(self, claims: JWTClaims, scope: str) -> None: ...
    def set_mfa_policy(self, project_id: str, mfa_required: bool) -> None: ...
    def get_mfa_policy(self, project_id: str) -> bool: ...
    def set_key_tier(self, key_id: str, tier: str) -> None: ...
    def consume_quota(self, key_id: str) -> bool: ...
    def get_quota_usage(self, key_id: str) -> dict[str, Any]: ...
